rosplan_demo_waypoints:
    # waypoints reference frame
    waypoint_frameid: map

    # waypoint 2D coordinates: x, y, theta
    wp0: [0.0, -0.1, 0.0]
    wp1: [-6.3, 0.5, 0.0]
    wp2: [-5.0, 3.0, 0.0]
    wp3: [2.5, 4.0, 0.0]
    wp4: [6.2, -0.5, 0.0]
    r1: [-6.5, -2.5, 0.0]
    r2: [-6.5, 2.5, 0.0]
    r3: [-2.0, 3.5, 0.0]
    r4: [1.0, 2.5, 0.0]
    r5: [5.0, 2.5, 0.0]
    r6: [5.5, -3.5, 0.0]

