(define (problem task)
(:domain inspection)
(:objects
    r1 r2 r3 r4 r5 r6 wp0 wp1 wp2 wp3 wp4 - waypoint
    kenny - robot
)
(:init
    (robot_at kenny wp0)

    (adjacent wp0 wp0)
    (adjacent wp1 wp1)
    (adjacent wp2 wp0)
    (adjacent wp0 wp2)
    (adjacent wp2 wp1)
    (adjacent wp1 wp2)
    (adjacent wp2 wp2)
    (adjacent wp3 wp0)
    (adjacent wp0 wp3)
    (adjacent wp3 wp3)
    (adjacent wp4 wp0)
    (adjacent wp0 wp4)
    (adjacent wp4 wp2)
    (adjacent wp2 wp4)
    (adjacent wp4 wp3)
    (adjacent wp3 wp4)
    (adjacent wp4 wp4)
    (adjacent r1 r1)
    (adjacent r2 r2)
    (adjacent r3 r3)
    (adjacent r4 r4)
    (adjacent r5 r5)
    (adjacent r6 r6)
    (adjacent wp0 r3)
    (adjacent r3 wp0)
    (adjacent wp0 r5)
    (adjacent r5 wp0)
    (adjacent wp1 r1)
    (adjacent r1 wp1)
    (adjacent wp1 r2)
    (adjacent r2 wp1)
    (adjacent wp2 r2)
    (adjacent r2 wp2)
    (adjacent wp2 r3)
    (adjacent r3 wp2)
    (adjacent wp3 r4)
    (adjacent r4 wp3)
    (adjacent wp3 r5)
    (adjacent r5 wp3)
    (adjacent wp4 r6)
    (adjacent r6 wp4)
    (adjacent wp4 r5)
    (adjacent r5 wp4)


    (is_room r1)
    (is_room r2)
    (is_room r3)
    (is_room r4)
    (is_room r5)
    (is_room r6)

)
(:goal (and
    (inspected r1)
    (inspected r2)
    (inspected r3)
    (inspected r4)
    (inspected r5)
    (inspected r6)
))
)
